dist: bionic
language: python
python:
  - "3.7"
env:
  - PYTHONPATH=.
install:
  - pip install -r requirements.txt
script:
  - pytest -rp -W ignore::DeprecationWarning
  - ./written_submission_helper.sh final_project_OptionA_answers.pdf
